-- TD-018: reqlog partition maintenance.
--
-- 00_baseline.sql pre-builds monthly partitions for reqlog.request_records /
-- reqlog.error_records from 2026-07 for seven months (through 2027-01) plus a
-- DEFAULT catch-all, and notes that "a maintenance job should roll this
-- forward once deployed". No such job existed. The failure mode is silent:
-- nothing errors when the explicit partitions run out, every row simply lands
-- in DEFAULT and keeps working - but drop-based retention, the entire reason
-- these tables are partitioned, stops being possible because expired rows are
-- no longer isolated in a droppable child.
--
-- These functions are the maintenance primitives. Running this file (via
-- db-init, the sole sanctioned structure-change path - see
-- 140-repo-governance-standard.md section 6) both installs them and extends
-- the runway immediately, so a single db-init run is a complete maintenance
-- pass.
--
-- Retention: 6 months (owner decision 2026-07-28, docs/30-design/
-- 210-usage-metering-and-history.md section 6). Rationale: twice the
-- platform's finest summary tier (usage_summary_hours, ~3 months) so
-- cross-quarter reconciliation and incident lookback both work, while
-- staying bounded - this is one row per request, not a rollup.

-- ---------------------------------------------------------------------------
-- ensure_partitions: create any missing monthly partition from the current
-- month through `months_ahead`. Idempotent - existing partitions are skipped,
-- so this is safe to run on any cadence, including twice in a row.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION reqlog.ensure_partitions(months_ahead int DEFAULT 12)
RETURNS TABLE (partition_name text, action text)
LANGUAGE plpgsql
AS $$
DECLARE
  parts text[] := ARRAY['request_records', 'error_records'];
  tbl text; child text; mn date; nm date; i int;
BEGIN
  IF months_ahead < 1 THEN
    RAISE EXCEPTION 'months_ahead must be >= 1 (got %)', months_ahead;
  END IF;

  FOREACH tbl IN ARRAY parts LOOP
    FOR i IN 0..months_ahead LOOP
      mn := date_trunc('month', now())::date + (i * interval '1 month');
      nm := mn + interval '1 month';
      child := tbl || '_y' || to_char(mn, 'YYYY') || 'm' || to_char(mn, 'MM');

      IF to_regclass(format('reqlog.%I', child)) IS NULL THEN
        EXECUTE format(
          'CREATE TABLE reqlog.%I PARTITION OF reqlog.%I FOR VALUES FROM (%L) TO (%L)',
          child, tbl, mn, nm);
        partition_name := child; action := 'created'; RETURN NEXT;
      ELSE
        partition_name := child; action := 'exists'; RETURN NEXT;
      END IF;
    END LOOP;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- drop_expired_partitions: detach then drop any monthly partition entirely
-- older than `retain_months`. DETACH first so a concurrent reader is not
-- holding a lock on the parent when the DROP lands.
--
-- Deliberately never touches the DEFAULT partition: rows there are, by
-- definition, ones whose proper partition was missing, and silently dropping
-- them would destroy exactly the evidence needed to notice that happened.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION reqlog.drop_expired_partitions(
  retain_months int,
  dry_run boolean DEFAULT true
)
RETURNS TABLE (partition_name text, action text)
LANGUAGE plpgsql
AS $$
DECLARE
  cutoff date;
  rec record;
BEGIN
  IF retain_months < 1 THEN
    RAISE EXCEPTION 'retain_months must be >= 1 (got %)', retain_months;
  END IF;

  cutoff := (date_trunc('month', now()) - (retain_months * interval '1 month'))::date;

  FOR rec IN
    SELECT c.relname AS child, parent.relname AS parent
    FROM pg_inherits inh
    JOIN pg_class c      ON c.oid = inh.inhrelid
    JOIN pg_class parent ON parent.oid = inh.inhparent
    JOIN pg_namespace n  ON n.oid = c.relnamespace
    WHERE n.nspname = 'reqlog'
      AND parent.relname IN ('request_records', 'error_records')
      AND c.relname ~ '_y[0-9]{4}m[0-9]{2}$'
    ORDER BY c.relname
  LOOP
    -- Reconstruct the partition's month from its own name; the suffix is
    -- generated by ensure_partitions above, so this is a closed loop.
    IF to_date(right(rec.child, 8), '"y"YYYY"m"MM') < cutoff THEN
      IF dry_run THEN
        partition_name := rec.child; action := 'would_drop'; RETURN NEXT;
      ELSE
        EXECUTE format('ALTER TABLE reqlog.%I DETACH PARTITION reqlog.%I',
                       rec.parent, rec.child);
        EXECUTE format('DROP TABLE reqlog.%I', rec.child);
        partition_name := rec.child; action := 'dropped'; RETURN NEXT;
      END IF;
    END IF;
  END LOOP;
END $$;

-- Extend the runway now, so applying this file is itself a maintenance pass.
-- 12 months ahead means a missed cadence degrades slowly and visibly (the
-- readiness check reports remaining runway) instead of falling off a cliff.
SELECT * FROM reqlog.ensure_partitions(12);

-- Expiry is NOT invoked here. Dropping data is a separate, deliberate act -
-- it must be an explicit db-init `partitions-prune` run with dry_run=false,
-- not a side effect of applying DDL.
